baseURL = "https://leeturner.me"
languageCode = "en-us"
title = "Lee Turner"
theme = "ananke"
#publishDir = "docs"
metaDataFormat = "yaml"
defaultContentLanguage = "en"
sectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-115883229-1"
enableRobotsTXT = true
disqusShortname = "leeturner-me"
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = "favicon.ico"
description = "Welcome to the lab - the place I write about my code experiments"
twitter = "https://twitter.com/leeturner"
github = "https://github.com/leeturner"
linkedin = "https://linkedin.com/in/turnerlee"

# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/default-hero.jpg"
custom_css = ["css/custom.css"]
recent_posts_number = 5
