baseURL = "/"
languageCode = "en-us"
builddrafts = false
canonifyurls = false
title = "Lee Turner"
author = "Lee Turner"
theme = "hugo-goa"
googleAnalytics = "UA-115883229-1"
enableRobotsTXT = true
disqusShortname = "leeturner-me"

[markup.goldmark.renderer]
unsafe = true

#[permalinks]
#post = "/blog/:title/"
#
[params]
author = "Hi, I'm Lee Turner 👋"
intro = "This is the personal site of Lee Turner"
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"
description = "Lead Backend Developer at [Crunch](https://medium.com/@crunchtech), [Snyk Ambassador](https://snyk.io/snyk-ambassadors/), Hacker of code. Appsec enthusiast. Runs [Brighton Kotlin](https://brightonkotlin.com) & [Brighton JUG](https://brightonjug.com)"
toc = false

## Site Meta Settings
[params.meta]
description = "Lead Backend Developer at Crunch, Snyk Ambassador, Hacker of code. Appsec enthusiast. Runs Brighton Kotlin & Brighton JUG"

## Social Accounts
[params.social]
github = "leeturner"
instagram = "lturner"
#xing = "<username>"
linkedin = "turnerlee"
twitter = "leeturner"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
youtube = "/UCpdN6W_x0jIJmJlBP9icORw"

## Extras
[params.extra]
copyright = "© 2021. Lee Turner | [Privacy Policy](/privacy)"
poweredby = true
highlightjs = true
socialmarkup = true
displayrssicon = false

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
name = "Home"
url = "/"
identifier = "home"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
identifier = "about"
weight = 2

[[menu.main]]
name = "Resume"
url = "https://leeturner.tech"
identifier = "resume"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts/"
identifier = "posts"
weight = 4

[[menu.main]]
name = "Projects"
url = "/projects/"
identifier = "projects"
weight = 5

[[menu.main]]
name = "Brighton Kotlin"
url = "/brighton-kotlin"
identifier = "brighton-kotlin"
weight = 6
