baseURL = "https://leeturner.me/"
languageCode = "en-us"
builddrafts = false
canonifyurls = false
title = "Lee Turner"
author = "Lee Turner"
theme = "hugo-theme-cleanwhite"
enableRobotsTXT = true
paginate = 6 #frontpage pagination
preserveTaxonomyNames = true
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[markup.goldmark.renderer]
unsafe = true

[params]
SEOTitle = "Lee Turner"
header_image = "img/headers/the_pinicles_perth_australia.png"
#author = "Hi, I'm Lee Turner 👋"
slogan = "A random stream of thoughts and software experiments"
description = "Senior Software Engineer at Segovia/Crown Agents Bank, Snyk Ambassador, Hacker of code. Appsec enthusiast. Runs Brighton Kotlin & Brighton JUG"
keyword = "lee, turner, lee turner, hacking, software engineering, security, coding"

# leancloud storage for page view counter
page_view_conter = false
leancloud_app_id = ""
leancloud_app_key = ""

# algolia site search
algolia_search = false
algolia_appId = ""
algolia_indexName = ""
algolia_apiKey = ""

# Sidebar settings
sidebar_about_description = "Hi, I'm Lee 👋.  Senior Software Engineer at Segovia/Crown Agents Bank, [Snyk Ambassador](https://snyk.io/snyk-ambassadors/), Hacker of code. Appsec enthusiast. Runs [Brighton Kotlin](https://brightonkotlin.com) & [Brighton JUG](https://brightonjug.com)"
sidebar_avatar = "img/avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

featured_tags = true
featured_condition_size = 1

image_404 = "img/404-bg.jpg"
title_404 = "The page you are looking for couldn't be found"
omit_categories = false

#Enable wechat pay & alipay to allow readers send reward money if they like the articles 
reward = false
friends = false
bookmarks = false
about_me = true

# Include any custom CSS and/or JS files, url or relative to /static folder
#custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
custom_js = ["https://buttons.github.io/buttons.js"]

## Social Accounts
[params.social]
rss = true
github = "https://github.com/leeturner"
mastodon = "https://hachyderm.io/@leeturner"
linkedin = "https://www.linkedin.com/in/turnerlee/"
twitter = "https://twitter.com/leeturner"
youtube = "https://youtube.com/@leeturner"
#instagram = "<username>"
#xing = "<username>"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"

## Extras
[params.extra]
copyright = "©2024. Lee Turner | [Privacy Policy](/privacy)"
poweredby = true
highlightjs = true
socialmarkup = true
displayrssicon = false

[[params.addtional_menus]]
title =  "Now"
href =  "/now"
[[params.addtional_menus]]
title =  "About"
href =  "/about"
[[params.addtional_menus]]
title =  "Projects"
href =  "/projects"
[[params.addtional_menus]]
title =  "Resume"
href =  "https://leeturner.tech"
[[params.addtional_menus]]
title =  "Archive"
href =  "/archive"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[params.giscus]
data_repo="leeturner/leeturner.me"
data_repo_id="MDEwOlJlcG9zaXRvcnkxMDMwNTIxNzQ="
data_category="General"
data_category_id="DIC_kwDOBiRzjs4CXhC_"
data_mapping="pathname"
data_reactions_enabled="1"
data_emit_metadata="0"
data_theme="light"
data_lang="en"
crossorigin="anonymous"

[markup]
[markup.tableOfContents]
endLevel = 2
startLevel = 1
[markup.highlight]
style = "dracula"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5
