baseURL = "https://leeturner.me"
languageCode = "en-us"
title = "Lee Turner"
theme = "ananke"
publishDir = "docs"
metaDataFormat = "yaml"
defaultContentLanguage = "en"
sectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-115883229-1"
enableRobotsTXT = true
disqusShortname = "leeturner-me"
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

